begin;
create extension if not exists pgtap with schema extensions;
select plan(31);

select has_table('public','support_conversations','company scoped support conversations exist');
select has_table('public','support_messages','support messages exist');
select has_table('public','support_issues','structured issues exist');
select has_table('public','developer_change_requests','admin change-request workflow exists');
select has_table('public','support_change_event_ledger','append-only support ledger exists');
select has_table('public','platform_change_owners','separate platform change-owner authority exists');
select has_table('public','support_notification_deliveries','durable owner notification outbox exists');
select has_column('public','support_triage_runs','actor_platform_user_id','cross-company triage records the platform actor');
select row_security_active('public.support_change_event_ledger','ledger uses RLS');
select row_security_active('public.support_notification_deliveries','notification outbox uses RLS');
select table_privs_are('public','support_change_event_ledger','authenticated',array[]::text[],'tenant users have no ledger table privileges');
select table_privs_are('public','developer_change_requests','authenticated',array['SELECT'],'tenant users cannot write change requests directly');
select table_privs_are('public','support_change_event_ledger','anon',array[]::text[],'anonymous users cannot forge ledger events');
select table_privs_are('public','platform_change_owners','authenticated',array[]::text[],'ordinary platform administrators cannot self-grant change-owner authority');
select table_privs_are('public','support_notification_deliveries','authenticated',array[]::text[],'customers cannot inspect or alter notification delivery state');
select function_privs_are('public','prepare_support_assistant_response(uuid,uuid,uuid)','authenticated',array[]::text[],'browser cannot prepare assistant runs');
select function_privs_are('public','finalize_support_assistant_response(uuid,uuid,uuid,text,jsonb,boolean)','authenticated',array[]::text[],'browser cannot finalize assistant runs');
select function_privs_are('public','prepare_support_triage(uuid,uuid)','authenticated',array[]::text[],'browser cannot prepare triage runs');
select function_privs_are('public','finalize_support_triage(uuid,uuid,uuid,text,text,boolean)','authenticated',array[]::text[],'browser cannot finalize triage runs');
select function_privs_are('public','create_support_issue_from_assistant_escalation(uuid,uuid)','authenticated',array[]::text[],'browser cannot forge Guide escalation issues');
select function_privs_are('public','submit_support_issue_as_actor(uuid,jsonb)','authenticated',array[]::text[],'browser cannot submit an issue for another actor');
select is(public.redact_support_diagnostics('{"page":"/jobs","token":"secret"}'::jsonb),'{"page":"/jobs"}'::jsonb,'support diagnostics are portable and redact secret-like keys');
select function_privs_are('public','create_support_conversation(text,text)','authenticated',array['EXECUTE'],'authenticated users can create support conversations through RPC');
select function_privs_are('public','create_developer_change_request(uuid,text)','authenticated',array['EXECUTE'],'admin-checked change request uses RPC');
select function_privs_are('public','approve_developer_change_request(uuid,text,text,text,integer)','authenticated',array['EXECUTE'],'approval is an owner-checked RPC, never a table write');
select function_privs_are('public','prepare_platform_change_request(uuid,text)','authenticated',array['EXECUTE'],'platform inbox can prepare a cross-company work order through RPC');
select col_is_pk('public','support_change_event_ledger','id','ledger has immutable event identity');
select has_check('public','developer_change_requests','developer change requests require a pending or reviewed state');
select col_is_fk('public','developer_change_requests','reviewed_by_profile_id','approval is bound to a company profile');
select col_is_fk('public','developer_change_requests','approved_by_platform_user_id','work-order approval is bound to a platform identity');
select has_trigger('public','support_issues','support_issue_recommendation_invalidates_approval','recommendation edits invalidate prior work-order approval');
select * from finish();
rollback;
