import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { MemoryRouter } from "react-router-dom";
import { AgencyClientDetails, AgencyClientsWorkspace } from "../src/pages/AgencyClientsPage";
import { RecruiterShell } from "../src/components/layout/RecruiterShell";
import type { AgencyClient } from "../src/services/agencyClientService";
const client: AgencyClient={id:"client",name:"Northstar",status:"active",contactName:"Sam",contactEmail:"sam@example.com",contactPhone:"123",notes:"<script>no</script>",canViewContacts:true,version:1,createdAt:"2026-09-19T00:00:00Z",updatedAt:"2026-09-19T00:00:00Z",createdByProfileId:"author",createdByName:"Author",updatedByProfileId:"author",updatedByName:"Author"};
const html=renderToStaticMarkup(<AgencyClientDetails client={client}/>);
assert.match(html,/Northstar/);assert.match(html,/sam@example.com/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/);
const restricted=renderToStaticMarkup(<AgencyClientDetails client={{...client,canViewContacts:false,contactName:null,contactEmail:null,contactPhone:null,notes:null}}/>);
assert.doesNotMatch(restricted,/Contact:|Email:|Phone:|sam@example/);
assert.match(renderToStaticMarkup(<AgencyClientDetails client={{...client,status:"archived"}}/>),/Archived client/);
const workspace=renderToStaticMarkup(<MemoryRouter><AgencyClientsWorkspace jobs={[]}/></MemoryRouter>);
assert.match(workspace,/does not create or merge an independent platform company/);assert.match(workspace,/Loading company client records/);assert.doesNotMatch(workspace,/<input/);
const shell=renderToStaticMarkup(<MemoryRouter><RecruiterShell active="clients" title="Clients" subtitle="Agency context" showHelp={false} showSignOut={false}><p>Content</p></RecruiterShell></MemoryRouter>);
assert.match(shell,/href="\/workspace\/clients"[^>]*>.*?Clients/s);
const app=readFileSync(new URL("../src/App.tsx",import.meta.url),"utf8");
const boundaryStart=app.indexOf('<Route element={<WorkspaceAccessBoundary />}>');
const clientRoute=app.indexOf('<Route path="/workspace/clients"');
const boundaryEnd=app.indexOf('</Route>',boundaryStart);
assert.ok(clientRoute>boundaryStart&&clientRoute<boundaryEnd,"Clients route must be behind authenticated company boundary");
console.log("Agency client rendering and authenticated route tests passed");
