import assert from "node:assert/strict";
import { getCandidateInterviewWorkspace, createCandidateInterviewItem, updateCandidateInterviewItem, updateCandidateInterviewPlan, listCandidateInterviewItemEvents, type CandidateInterviewRpcClient } from "../src/services/candidateInterviewService";
async function main() {
  const applicationId = "10000000-0000-0000-0000-000000000001", itemId = "20000000-0000-0000-0000-000000000001", profileId = "30000000-0000-0000-0000-000000000001", criterionId = "40000000-0000-0000-0000-000000000001", requestId = "50000000-0000-0000-0000-000000000001";
  const criterion = {id: criterionId, label: "Maintain a project tracker", description: "Weekly Excel updates", priority: "required"};
  const row = {id: itemId, application_id: applicationId, criterion_id: criterionId, criterion_snapshot: criterion, question: "How did you track overdue tasks?", candidate_answer: "", reviewer_observation: "", source_reference: "", verification_state: "not_checked", author_profile_id: profileId, author_name: "Original reviewer", updated_by_profile_id: profileId, updated_by_name: "Latest reviewer", version: 1, created_at: "2026-09-19T10:00:00.000000+00:00", updated_at: "2026-09-19T10:00:00Z"};
  const workspace = {application_id: applicationId, current_profile_id: profileId, can_edit: true, planned_at: null, plan_version: 0, criteria: [criterion], items: [row], plan_events: []};
  const event = {id: requestId, item_id: itemId, actor_profile_id: null, actor_name: "Former reviewer", previous_state: null, state: row, created_at: row.created_at};
  const calls: Array<{name: string; args?: Record<string, unknown>}> = [];
  const client: CandidateInterviewRpcClient = {rpc: async (name, args) => { calls.push({name, args}); return {error: null, data: name === "get_candidate_interview_workspace" ? workspace : name === "list_candidate_interview_item_events" ? [event] : name === "update_candidate_interview_plan" ? {application_id: applicationId, planned_at: args?.p_planned_at, version: 1, updated_at: row.updated_at} : row}; }};
  const result = await getCandidateInterviewWorkspace(applicationId, client);
  assert.equal(result.planVersion, 0); assert.equal(result.items[0].criterionSnapshot.label, criterion.label);
  const input = {applicationId, criterionId, requestId, question: " How did you track overdue tasks? ", candidateAnswer: "", reviewerObservation: "", sourceReference: "", verificationState: "not_checked" as const};
  await createCandidateInterviewItem(input, client); await createCandidateInterviewItem(input, client);
  assert.deepEqual(calls[1].args, calls[2].args, "Create retries preserve the caller's request ID");
  assert.equal(calls[1].args?.p_question, row.question);
  assert.equal("p_criterion_snapshot" in (calls[1].args ?? {}), false, "Snapshot is selected by the server");
  await updateCandidateInterviewItem({...input, itemId, expectedVersion: 1}, client);
  assert.equal(calls[3].args?.p_expected_version, 1);
  assert.equal("p_criterion_id" in (calls[3].args ?? {}), false, "Criterion cannot be changed when editing answers");
  const plan = await updateCandidateInterviewPlan({applicationId, plannedAt: "2026-10-01T10:00:00+08:00", expectedVersion: 0}, client);
  assert.equal(plan.plannedAt, "2026-10-01T02:00:00.000Z");
  assert.equal((await listCandidateInterviewItemEvents(itemId, client))[0].actorName, "Former reviewer");
  const count = calls.length;
  for (const patch of [{question: ""}, {candidateAnswer: "x".repeat(4001)}, {sourceReference: "x".repeat(2001)}, {verificationState: "candidate_explained" as const}, {verificationState: "supporting_evidence_added" as const}]) await assert.rejects(() => createCandidateInterviewItem({...input, ...patch}, client));
  await assert.rejects(() => updateCandidateInterviewPlan({applicationId, plannedAt: "2026-02-30T10:00:00Z", expectedVersion: 0}, client), /valid interview date/);
  await assert.rejects(() => updateCandidateInterviewPlan({applicationId, plannedAt: "2026-10-01T10:00", expectedVersion: 0}, client), /timezone/);
  await assert.rejects(() => updateCandidateInterviewItem({...input, itemId, expectedVersion: 0}, client), /Reload/);
  assert.equal(calls.length, count, "Invalid input never reaches the server");
  const responseClient = (data: unknown): CandidateInterviewRpcClient => ({rpc: async () => ({data, error: null})});
  for (const patch of [{created_at: "2026-02-30T10:00:00Z"}, {version: 0}, {verification_state: "unknown"}, {candidate_answer: "x".repeat(4001)}, {criterion_snapshot: {...criterion, id: profileId}}, {updated_by_profile_id: undefined}, {application_id: profileId}, {verification_state: "candidate_explained"}]) await assert.rejects(() => getCandidateInterviewWorkspace(applicationId, responseClient({...workspace, items: [{...row, ...patch}]})), /invalid/);
  const planHistory = {id: requestId, application_id: applicationId, actor_profile_id: null, actor_name: "Scheduler", previous_state: {application_id: applicationId, planned_at: null, version: 0, updated_at: null}, state: {application_id: applicationId, planned_at: row.created_at, version: 1, updated_at: row.created_at}, created_at: row.created_at};
  assert.equal((await getCandidateInterviewWorkspace(applicationId, responseClient({...workspace, plan_events: [planHistory]}))).planEvents[0].actorName, "Scheduler");
  await assert.rejects(() => getCandidateInterviewWorkspace(applicationId, responseClient({...workspace, plan_events: [{...planHistory, application_id: criterionId}]})), /invalid/);
  const historical = await getCandidateInterviewWorkspace(applicationId, responseClient({...workspace, criteria: [], items: [{...row, criterion_id: null, author_profile_id: null, updated_by_profile_id: null, author_email: "private@example.com"}]}));
  assert.equal(historical.items[0].criterionSnapshot.label, criterion.label, "Deleted criteria retain the historical snapshot");
  assert.equal(historical.items[0].authorName, "Original reviewer");
  assert.equal("author_email" in historical.items[0], false);
  for (const [code, message] of [["INTERVIEW_VERSION_CONFLICT", /Another reviewer/], ["INTERVIEW_WRITE_ACCESS_REQUIRED", /does not currently allow/], ["INTERVIEW_CRITERION_UNAVAILABLE", /current criterion/]] as const) await assert.rejects(() => createCandidateInterviewItem(input, {rpc: async () => ({data: null, error: {message: code}})}), message);
  await assert.rejects(() => listCandidateInterviewItemEvents(itemId, responseClient([{...event, item_id: criterionId}])), /invalid/);
  console.log("Candidate interview service tests passed.");
}
void main();
