import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { CandidateWorkflowPanel, CandidateWorkflowActivity, uniqueWorkflowCandidates, workflowIsOverdue, workflowLocalDate, workflowChanges, workflowSubmittedDue } from "../src/components/workflow/CandidateWorkflowPanel";
import type { CandidateWorkflow } from "../src/services/candidateWorkflowService";
const state: CandidateWorkflow = { applicationId: "app-one", stage: "interview", assignedProfileId: "reviewer-one", nextAction: "Confirm deployment ownership", dueAt: "2026-09-01T12:00:00.000Z", version: 2, updatedAt: "2026-09-01T12:00:00.000Z" };
const before: CandidateWorkflow = { ...state, stage: "evidence_review", assignedProfileId: null, nextAction: "", dueAt: null, version: 1 };
assert.equal(uniqueWorkflowCandidates([{ applicationId: "a", candidateName: "A" }, { applicationId: "a", candidateName: "A" }, { applicationId: "b", candidateName: "B" }]).length, 2, "Duplicate reports must not duplicate a candidate workflow");
assert.equal(workflowIsOverdue(state, Date.parse("2026-09-02T00:00:00Z")), true);
assert.equal(workflowIsOverdue({ ...state, stage: "closed" }, Date.parse("2026-09-02T00:00:00Z")), false, "Closed work is not overdue");
assert.equal(workflowIsOverdue({ ...state, dueAt: null }), false);
assert.equal(workflowLocalDate(null), "");
assert.equal(new Date(workflowLocalDate(state.dueAt)).toISOString(), state.dueAt, "UTC date renders as local wall time and round-trips");
assert.deepEqual(workflowChanges(before, state, [{ id: "reviewer-one", name: "Sam", isActive: true }]).slice(0, 3), ["Stage: Evidence review → Interview", "Reviewer: Unassigned → Sam", "Next action: Confirm deployment ownership"]);
const submitted = new FormData();
submitted.set("workflowDue", "2026-10-01T10:00");
assert.deepEqual(workflowSubmittedDue(submitted), { local: "2026-10-01T10:00", utc: new Date("2026-10-01T10:00").toISOString() }, "Save reads native submitted date even when React change did not fire");
submitted.set("workflowDue", "");
assert.deepEqual(workflowSubmittedDue(submitted), { local: "", utc: null }, "Clearing a native date field clears the saved due date");
submitted.set("workflowDue", "invalid");
assert.throws(() => workflowSubmittedDue(submitted), /valid due date/);
const originalTimezone = process.env.TZ;
try {
  process.env.TZ = "Australia/Sydney";
  submitted.set("workflowDue", "2026-10-04T02:30");
  assert.throws(() => workflowSubmittedDue(submitted), /local time does not exist/, "Spring-forward gap must not silently shift a recruiter's due time");
  submitted.set("workflowDue", "2026-10-04T03:30");
  assert.equal(workflowSubmittedDue(submitted).utc, "2026-10-03T16:30:00.000Z");
  submitted.set("workflowDue", "2026-09-19T10:00");
  assert.equal(workflowSubmittedDue(submitted).utc, "2026-09-19T00:00:00.000Z");
  process.env.TZ = "Asia/Singapore";
  submitted.set("workflowDue", "2026-10-04T02:30");
  assert.equal(workflowSubmittedDue(submitted).utc, "2026-10-03T18:30:00.000Z");
} finally {
  if (originalTimezone === undefined) delete process.env.TZ;
  else process.env.TZ = originalTimezone;
}
const activity = renderToStaticMarkup(<CandidateWorkflowActivity events={[{ id: "event-one", actorProfileId: "reviewer-one", actorName: "Sam", previousState: before, state, createdAt: "2026-09-01T12:00:00.000Z" }]} reviewers={[{ id: "reviewer-one", name: "Sam", isActive: false }]} />);
assert.match(activity, /Sam/);
assert.match(activity, /Evidence review → Interview/);
assert.match(activity, /Confirm deployment ownership/);
assert.match(activity, /dateTime="2026-09-01T12:00:00.000Z"/);
assert.match(renderToStaticMarkup(<CandidateWorkflowActivity events={[]} reviewers={[]} />), /No workflow changes recorded/);
const panel = renderToStaticMarkup(<CandidateWorkflowPanel jobId="job-one" candidates={[]} />);
assert.match(panel, /Loading candidate workflow/);
assert.match(panel, /Stages do not change hiring decisions/);
assert.match(panel, /do not send automatic reminders/);
assert.doesNotMatch(panel, /Save workflow/, "Do not expose mutations until access loads");
console.log("Candidate workflow rendering and view rules passed");
