import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { CandidateInternalNoteContent, CandidateInternalNotesPanel, internalNoteKindLabels } from "../src/components/workflow/CandidateInternalNotesPanel";
import type { CandidateInternalNote } from "../src/services/candidateInternalNotesService";
const note: CandidateInternalNote = { id: "note-a", applicationId: "application-a", kind: "candidate_statement", body: 'Candidate said: <script>alert("private")</script>\nNeeds reference verification.', authorProfileId: "author-a", authorName: "Sam Recruiter", createdAt: "2026-09-19T01:00:00Z", updatedAt: "2026-09-19T02:00:00Z", version: 2, canEdit: true };
const html = renderToStaticMarkup(<CandidateInternalNoteContent note={note} />);
assert.match(html, /Candidate explanation/);
assert.match(html, /Sam Recruiter/);
assert.match(html, /Edited/);
assert.match(html, /dateTime="2026-09-19T02:00:00Z"/);
assert.match(html, /&lt;script&gt;/, "Note content must render as plain text");
assert.doesNotMatch(html, /<script>/);
const original = renderToStaticMarkup(<CandidateInternalNoteContent note={{ ...note, version: 1, authorName: "" }} />);
assert.doesNotMatch(original, /Edited/);
assert.match(original, /Former reviewer/);
const panel = renderToStaticMarkup(<CandidateInternalNotesPanel applicationId="application-a" candidateName="Lee" />);
assert.match(panel, /Visible to authorised members of your company/);
assert.match(panel, /Excluded from client summaries and shared reports/);
assert.match(panel, /Loading internal notes/);
assert.doesNotMatch(panel, /<textarea/, "Composer remains inaccessible until server permissions load");
assert.deepEqual(Object.values(internalNoteKindLabels), ["Candidate explanation", "Reviewer observation", "Verification record"]);
console.log("Candidate internal notes render tests passed");
