import React, { useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { RecruiterShell } from "../components/layout/RecruiterShell";
import { getAsyncHiringRepository } from "../services/hiringRepository";
import { listAgencyClients, createAgencyClient, updateAgencyClient, getJobClientContext, updateJobClientContext, listAgencyClientEvents, listJobClientContextEvents, type AgencyClient, type AgencyClientFields, type AgencyClientsList, type JobClientContext } from "../services/agencyClientService";
export const agencyClientsPageService = { listAgencyClients, createAgencyClient, updateAgencyClient, getJobClientContext, updateJobClientContext, listAgencyClientEvents, listJobClientContextEvents };
type Job = { id: string; title: string };
const blank: AgencyClientFields = { name:"", contactName:"", contactEmail:"", contactPhone:"", notes:"" };
function errorText(error: unknown) { return error instanceof Error ? error.message : "Client records could not be loaded or saved. Please try again."; }
export function AgencyClientDetails({ client }: { client: AgencyClient }) {
  return <><h3>{client.name}</h3><p>{client.status === "active" ? "Active client" : "Archived client"}</p>{client.contactName !== null && <p>Contact: {client.contactName || "Not recorded"}</p>}{client.contactEmail !== null && <p>Email: {client.contactEmail || "Not recorded"}</p>}{client.contactPhone !== null && <p>Phone: {client.contactPhone || "Not recorded"}</p>}{client.notes !== null && <p className="agency-client-notes">{client.notes || "No internal client notes"}</p>}</>;
}
export function AgencyClientsWorkspace({ jobs, service = agencyClientsPageService }: { jobs: Job[]; service?: typeof agencyClientsPageService }) {
  const [clientHistory,setClientHistory]=useState<Awaited<ReturnType<typeof listAgencyClientEvents>>>([]);
  const [historyClient,setHistoryClient]=useState("");
  const [historyError,setHistoryError]=useState("");
  const [historyLoading,setHistoryLoading]=useState(false);
  const [contextEvents,setContextEvents]=useState<Awaited<ReturnType<typeof listJobClientContextEvents>>>([]);
  const historyGeneration=useRef(0);
  const generation=useRef(0);
  const jobGeneration=useRef(0);
  const createRequest=useRef<{signature:string;id:string}|null>(null);
  const editorHeading=useRef<HTMLHeadingElement>(null);
  const [data,setData]=useState<AgencyClientsList|null>(null);
  const [loadError,setLoadError]=useState("");
  const [reload,setReload]=useState(0);
  const [filter,setFilter]=useState<"all"|"active"|"archived">("active");
  const [draft,setDraft]=useState<AgencyClientFields>(blank);
  const [editing,setEditing]=useState<AgencyClient|null>(null);
  const [status,setStatus]=useState<"active"|"archived">("active");
  const [busy,setBusy]=useState(false);
  const [saveError,setSaveError]=useState("");
  const [notice,setNotice]=useState("");
  const [jobId,setJobId]=useState("");
  const [contextValue,setContext]=useState<JobClientContext|null>(null);
  const [contextError,setContextError]=useState("");
  const [contextBusy,setContextBusy]=useState(false);
  const [selectedClient,setSelectedClient]=useState("");
  const [contextNotice,setContextNotice]=useState("");
  const [contextReload,setContextReload]=useState(0);
  const context=contextValue?.jobId===jobId?contextValue:null;
  useEffect(()=>{const token=++generation.current;setData(null);setLoadError("");setDraft(blank);setEditing(null);setBusy(false);setSaveError("");setNotice("");createRequest.current=null;service.listAgencyClients().then(value=>{if(generation.current===token)setData(value);}).catch(error=>{if(generation.current===token)setLoadError(errorText(error));});return()=>{generation.current++;historyGeneration.current++;};},[reload,service]);
  useEffect(()=>{const token=++jobGeneration.current;setContext(null);setContextEvents([]);setContextError("");setContextNotice("");setSelectedClient("");setContextBusy(false);if(!jobId)return;Promise.all([service.getJobClientContext(jobId),service.listJobClientContextEvents(jobId)]).then(([value,events])=>{if(jobGeneration.current===token){setContext(value);setContextEvents(events);setSelectedClient(value.clientId??"");}}).catch(error=>{if(jobGeneration.current===token)setContextError(errorText(error));});return()=>{jobGeneration.current++;};},[jobId,contextReload,service]);
  const dirty=!!editing||Object.values(draft).some(Boolean);
  function edit(client:AgencyClient){setEditing(client);setStatus(client.status);setDraft({name:client.name,contactName:client.contactName??"",contactEmail:client.contactEmail??"",contactPhone:client.contactPhone??"",notes:client.notes??""});setNotice("");setSaveError("");editorHeading.current?.focus();}
  async function save(event:React.FormEvent){event.preventDefault();if(!data?.canManage||busy)return;const token=generation.current;setBusy(true);setSaveError("");setNotice("");try{const signature=JSON.stringify(draft);if(!createRequest.current||createRequest.current.signature!==signature)createRequest.current={signature,id:crypto.randomUUID()};const result=editing?await service.updateAgencyClient({...draft,clientId:editing.id,status,expectedVersion:editing.version}):await service.createAgencyClient({...draft,requestId:createRequest.current.id});if(generation.current!==token)return;setData(previous=>previous?{...previous,clients:previous.clients.some(client=>client.id===result.id)?previous.clients.map(client=>client.id===result.id?result:client):[result,...previous.clients]}:previous);setDraft(blank);setEditing(null);createRequest.current=null;setNotice(result.status==="archived"?"Client archived. Existing role context is retained; this client cannot be newly assigned.":"Client record saved within your company workspace.");setContext(previous=>previous?.clientId===result.id?{...previous,client:{id:result.id,name:result.name,status:result.status}}:previous);if(historyClient===result.id)void showClientHistory(result.id);}catch(error){if(generation.current===token)setSaveError(errorText(error));}finally{if(generation.current===token)setBusy(false);}}
  async function saveContext(event:React.FormEvent){event.preventDefault();if(!context?.canManage||contextBusy)return;const token=jobGeneration.current;setContextBusy(true);setContextError("");setContextNotice("");try{const result=await service.updateJobClientContext({jobId,clientId:selectedClient||null,expectedVersion:context.version});if(jobGeneration.current!==token)return;setContext(result);setSelectedClient(result.clientId??"");try { const events=await service.listJobClientContextEvents(jobId); if(jobGeneration.current===token)setContextEvents(events); } catch { if(jobGeneration.current===token)setContextError("Role context saved, but history could not be refreshed. Reload role context to verify it."); } if(jobGeneration.current!==token)return;setContextNotice("Role client context saved. Candidate decisions and company access are unchanged.");}catch(error){if(jobGeneration.current===token)setContextError(errorText(error));}finally{if(jobGeneration.current===token)setContextBusy(false);}}
  async function showClientHistory(clientId:string){const token=++historyGeneration.current;setHistoryClient(clientId);setClientHistory([]);setHistoryError("");setHistoryLoading(true);try{const events=await service.listAgencyClientEvents(clientId);if(historyGeneration.current===token)setClientHistory(events);}catch(error){if(historyGeneration.current===token)setHistoryError(errorText(error));}finally{if(historyGeneration.current===token)setHistoryLoading(false);}}
  return <div className="agency-clients-workspace"><section className="next-task"><p className="section-kicker">Agency client records</p><h2>Keep each client and role in context</h2><p>These records belong to your agency’s company workspace. Adding a client does not create or merge an independent platform company, provide a client portal, or send an invitation.</p></section>
    {loadError?<div className="workspace-card" role="alert"><p>{loadError}</p><button type="button" className="button" onClick={()=>setReload(value=>value+1)}>Retry clients</button></div>:!data?<p role="status">Loading company client records…</p>:<>
      {data.canManage?<section className="workspace-card"><h2 ref={editorHeading} tabIndex={-1}>{editing?"Edit client record":"Add a client"}</h2><form onSubmit={save}><fieldset disabled={busy}><label>Client organisation name<input required maxLength={200} value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})} placeholder="Northstar Logistics"/></label>{(!editing||editing.canViewContacts)&&<><div className="agency-client-fields"><label>Contact name<input maxLength={200} value={draft.contactName} onChange={event=>setDraft({...draft,contactName:event.target.value})}/></label><label>Contact email<input type="email" maxLength={254} value={draft.contactEmail} onChange={event=>setDraft({...draft,contactEmail:event.target.value})}/></label><label>Contact phone<input type="tel" maxLength={80} value={draft.contactPhone} onChange={event=>setDraft({...draft,contactPhone:event.target.value})}/></label></div><label>Internal client notes<textarea maxLength={2000} value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})} placeholder="Recruitment contact and job-related working arrangements."/></label></>}{editing&&<label>Client status<select value={status} onChange={event=>setStatus(event.target.value as typeof status)}><option value="active">Active</option><option value="archived">Archived</option></select></label>}{editing&&status==="archived"&&<p>Archiving retains existing role associations and history. The client will be unavailable for new assignments.</p>}</fieldset><div className="workflow-actions"><button type="submit" className="button button-primary" disabled={busy||!draft.name.trim()}>{busy?"Saving client…":editing?"Save client changes":"Create client record"}</button>{dirty&&<button type="button" className="button" disabled={busy} onClick={()=>{setDraft(blank);setEditing(null);setSaveError("");createRequest.current=null;}}>Discard client draft</button>}</div></form>{saveError&&<div role="alert"><p>{saveError} Your draft remains available.</p><button type="button" className="button" disabled={busy} onClick={()=>setReload(value=>value+1)}>Discard draft and reload clients</button></div>}{notice&&<p role="status">{notice}</p>}</section>:<section className="workspace-card"><p>Client records are read only for your access. Private contact details are shown only when your company permissions allow them.</p></section>}
      <section className="workspace-card"><h2>Company clients</h2><label>Show clients<select value={filter} onChange={event=>setFilter(event.target.value as typeof filter)}><option value="active">Active</option><option value="archived">Archived</option><option value="all">All clients</option></select></label>{data.clients.filter(client=>filter==="all"||client.status===filter).length?<ul className="agency-client-list">{data.clients.filter(client=>filter==="all"||client.status===filter).map(client=><li key={client.id}><AgencyClientDetails client={client}/>{data.canManage&&<button type="button" className="button" disabled={busy||dirty} onClick={()=>edit(client)}>Edit {client.name}</button>} <button type="button" className="button" onClick={()=>void showClientHistory(client.id)}>View history</button>{historyClient===client.id&&<div><h4>Client history</h4>{historyLoading?<p role="status">Loading client history…</p>:historyError?<p role="alert">{historyError}</p>:<ol>{clientHistory.map(event=><li key={event.id}><p>{event.actorName} · <time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString()}</time></p><AgencyClientDetails client={event.state}/></li>)}</ol>}</div>}</li>)}</ul>:<p>No {filter==="all"?"":filter+" "}client records yet.</p>}</section>
      <section className="workspace-card"><h2>Assign a client to a role</h2><p>A role can have one optional client context. Candidates and records remain inside your company workspace.</p>{jobs.length?<label>Company role<select value={jobId} disabled={contextBusy} onChange={event=>setJobId(event.target.value)}><option value="">Choose a role</option>{jobs.map(job=><option key={job.id} value={job.id}>{job.title}</option>)}</select></label>:<p>No roles available. <Link to="/jobs">Create a job</Link> before assigning client context.</p>}{jobId&&!context&&!contextError&&<p role="status">Loading role client context…</p>}{context&&<><p>Current client: {context.client?`${context.client.name}${context.client.status==="archived"?" (archived)":""}`:"No client assigned"}</p>{context.canManage?<form onSubmit={saveContext}><label>Client for this role<select value={selectedClient} disabled={contextBusy||busy} onChange={event=>setSelectedClient(event.target.value)}><option value="">No client / unassign</option>{data.clients.filter(client=>client.status==="active").map(client=><option key={client.id} value={client.id}>{client.name}</option>)}{context.client?.status==="archived"&&<option value={context.client.id} disabled>{context.client.name} (archived — choose another or unassign)</option>}</select></label><button type="submit" className="button button-primary" disabled={contextBusy||busy||selectedClient===(context.clientId??"")}>{contextBusy?"Saving role context…":"Save role client"}</button></form>:<p>Role client context is read only for your access.</p>}<details><summary>Role client context history</summary>{contextEvents.length?<ol>{contextEvents.map(event=><li key={event.id}><p>{event.actorName} · <time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString()}</time></p><p>{event.state.client?`Assigned to ${event.state.client.name}`:"Client context removed"}</p></li>)}</ol>:<p>No role client context changes recorded.</p>}</details></>}{contextError&&<div role="alert"><p>{contextError}</p><button type="button" className="button" disabled={contextBusy} onClick={()=>setContextReload(value=>value+1)}>Discard selection and reload role context</button></div>}{contextNotice&&<p role="status">{contextNotice}</p>}</section>
    </>}
  </div>;
}
export function AgencyClientsPage(){const repository=useMemo(()=>getAsyncHiringRepository(),[]);const [jobs,setJobs]=useState<Job[]|null>(null);const [reviewerName,setReviewerName]=useState("Reviewer");const [error,setError]=useState("");const [reload,setReload]=useState(0);useEffect(()=>{let active=true;setJobs(null);setError("");repository.getActiveCompanyContext().then(async context=>{const dashboard=await repository.getDashboardData(context.companyId,context.userId);if(active){setReviewerName(context.userName);setJobs(dashboard.recentJobs.map(job=>({id:job.id,title:job.title})));}}).catch(reason=>{if(active)setError(errorText(reason));});return()=>{active=false;};},[repository,reload]);return <RecruiterShell active="clients" title="Clients" subtitle="Manage agency-owned client records and role context." reviewerName={reviewerName}><main className="workspace-content">{error?<section className="workspace-card" role="alert"><p>{error}</p><button className="button" type="button" onClick={()=>setReload(value=>value+1)}>Retry company workspace</button></section>:jobs?<AgencyClientsWorkspace jobs={jobs}/>:<p role="status">Checking company roles and access…</p>}</main></RecruiterShell>;}
