export const clientHandoffStyles = `.client-handoff-overlay{position:fixed;inset:0;z-index:1000;overflow:auto;background:#e9ede9;padding:24px;color:#172d27}
.client-handoff-controls{max-width:900px;margin:0 auto 24px;display:flex;align-items:center;gap:16px;flex-wrap:wrap}
.client-handoff-controls>div{flex:1 1 65%}.client-handoff-controls label{flex:1 1 60%;display:flex;gap:8px;align-items:center}
.client-handoff-document{max-width:900px;margin:auto;background:#fff;padding:48px;line-height:1.6;font-size:16px;border:1px solid #bbc8c0}
.client-handoff-document header{border-bottom:3px solid #204b3f;padding-bottom:16px;margin-bottom:24px}.client-handoff-document h1{font-size:32px}.client-handoff-document h2{font-size:23px;margin:24px 0 12px}.client-handoff-document h3{font-size:18px}
.client-handoff-document section{border-bottom:1px solid #d4ddd7;padding:16px 0;overflow-wrap:anywhere}.client-handoff-document header,.client-handoff-document footer{border-color:var(--client-accent,#204b3f)}.client-handoff-document footer{border-top:2px solid var(--client-accent,#204b3f);margin-top:32px;padding-top:16px;font-size:13px}.client-handoff-logo{display:block;max-height:56px;max-width:180px;object-fit:contain;margin-bottom:14px}
.client-share-controls{max-width:900px;margin:24px auto;background:white;padding:28px;border:1px solid #bbc8c0}.client-share-controls label{display:flex;gap:10px;align-items:center;margin:14px 0}.client-share-controls label:not(:has(input[type=checkbox])){align-items:flex-start;flex-direction:column}.client-share-controls input:not([type=checkbox]),.client-share-controls select,.client-share-controls textarea{width:100%;max-width:720px}.client-share-controls textarea{min-height:90px}.client-share-controls input[readonly]{width:100%;min-width:150px}.client-share-controls li{margin:16px 0}.sharing-authority{border-top:6px solid #28543f}.sharing-authority-revoke{margin-top:24px;padding-top:18px;border-top:1px solid #bbc8c0}.client-shared-page{padding:28px;background:#e9ede9}.client-shared-notice{max-width:900px;margin:0 auto 24px}
@media print{.client-share-controls{display:none!important}}
@media(max-width:600px){.client-handoff-overlay{padding:12px}.client-handoff-document{padding:22px}}
@media print{body:has(.client-handoff-overlay)>:not(.client-handoff-overlay){display:none!important}body:has(.client-handoff-overlay){overflow:visible!important}.client-handoff-overlay{position:static!important;overflow:visible!important;padding:0;background:white}.client-handoff-controls{display:none!important}.client-handoff-document{border:0;padding:0;max-width:none;font-size:10pt;color:#000}.client-handoff-document h1{font-size:22pt}.client-handoff-document h2{font-size:15pt;break-after:avoid}.client-handoff-document h3{font-size:12pt;break-after:avoid}.client-handoff-document section{break-inside:avoid}.client-handoff-document header{break-inside:avoid}@page{margin:18mm}}
`;
