import React, { useEffect, useId, useRef, useState } from "react";
import { getCandidateInterviewWorkspace, createCandidateInterviewItem, updateCandidateInterviewItem, updateCandidateInterviewPlan, listCandidateInterviewItemEvents, candidateInterviewVerificationLabels, CANDIDATE_INTERVIEW_VERIFICATION_STATES } from "../../services/candidateInterviewService";
export const candidateInterviewPanelService = { getCandidateInterviewWorkspace, createCandidateInterviewItem, updateCandidateInterviewItem, updateCandidateInterviewPlan, listCandidateInterviewItemEvents };
type Workspace = Awaited<ReturnType<typeof getCandidateInterviewWorkspace>>;
type Item = Workspace["items"][number];
type Events = Awaited<ReturnType<typeof listCandidateInterviewItemEvents>>;
type Draft = Pick<Item, "question" | "candidateAnswer" | "reviewerObservation" | "sourceReference" | "verificationState"> & { criterionId: string };
const emptyDraft: Draft = { criterionId: "", question: "", candidateAnswer: "", reviewerObservation: "", sourceReference: "", verificationState: "not_checked" };
function localDate(value: string | null) { if (!value) return ""; const d = new Date(value); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}T${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`; }
export function interviewPlannedAt(value: string): string | null { if (!value) return null; const date = new Date(value); if (!Number.isFinite(date.getTime()) || localDate(date.toISOString()) !== value) throw new Error("Choose a valid local interview time. This time may not exist in your timezone."); return date.toISOString(); }
function dateLabel(value: string) { return new Date(value).toLocaleString(undefined, { year:"numeric", month:"short", day:"numeric", hour:"2-digit", minute:"2-digit", timeZoneName:"short" }); }
function errorText(error: unknown) { return error instanceof Error ? error.message : "Interview workspace could not be loaded or saved. Try again."; }
export function interviewUnresolvedItems(items: Item[]) { return items.filter(item => item.verificationState !== "supporting_evidence_added"); }
export function CandidateInterviewRecord({ item }: { item: Item }) {
  return <><h4>{item.criterionSnapshot.label}</h4><p>{item.criterionSnapshot.description}</p><p><strong>{candidateInterviewVerificationLabels[item.verificationState]}</strong></p><dl><dt>Question</dt><dd>{item.question}</dd><dt>Candidate answer</dt><dd>{item.candidateAnswer || "No answer recorded"}</dd><dt>Reviewer observation</dt><dd>{item.reviewerObservation || "No observation recorded"}</dd><dt>Source / reference</dt><dd>{item.sourceReference || "No source recorded"}</dd></dl><p className="internal-note-meta">Added by {item.authorName || "Former reviewer"} · <time dateTime={item.createdAt}>{dateLabel(item.createdAt)}</time>{item.version > 1 && <> · Edited by {item.updatedByName || "Former reviewer"} · <time dateTime={item.updatedAt}>{dateLabel(item.updatedAt)}</time></>}</p></>;
}
export function CandidateInterviewPanel({ applicationId, candidateName, onClose, service = candidateInterviewPanelService }: { applicationId:string; candidateName:string; onClose?:()=>void; service?:typeof candidateInterviewPanelService }) {
  const id = useId();
  const heading = useRef<HTMLHeadingElement>(null);
  const composer = useRef<HTMLHeadingElement>(null);
  const generation = useRef(0);
  const eventGeneration = useRef(0);
  const request = useRef<{ signature:string; id:string } | null>(null);
  const [data,setData] = useState<Workspace|null>(null);
  const [loaded,setLoaded] = useState("");
  const [reload,setReload] = useState(0);
  const [loadError,setLoadError] = useState("");
  const [draft,setDraft] = useState<Draft>(emptyDraft);
  const [editing,setEditing] = useState<Item|null>(null);
  const [planned,setPlanned] = useState("");
  const [busy,setBusy] = useState<"plan"|"item"|null>(null);
  const [saveError,setSaveError] = useState("");
  const [notice,setNotice] = useState("");
  const [historyItem,setHistoryItem] = useState("");
  const [events,setEvents] = useState<Events>([]);
  const [historyBusy,setHistoryBusy] = useState(false);
  const [historyError,setHistoryError] = useState("");
  useEffect(()=>{ const token=++generation.current; request.current=null; setData(null);setLoadError("");setDraft(emptyDraft);setEditing(null);setPlanned("");setBusy(null);setSaveError("");setNotice("");setHistoryItem("");setEvents([]);
    service.getCandidateInterviewWorkspace(applicationId).then(value=>{if(generation.current===token){setData(value);setLoaded(applicationId);setPlanned(localDate(value.plannedAt));}}).catch(error=>{if(generation.current===token)setLoadError(errorText(error));});
    return()=>{generation.current++;eventGeneration.current++;};
  },[applicationId,reload,service]);
  useEffect(()=>{heading.current?.focus();},[applicationId]);
  const current=loaded===applicationId?data:null;
  const dirty=!!editing || Object.keys(emptyDraft).some(key=>draft[key as keyof Draft]!==emptyDraft[key as keyof Draft]);
  async function savePlan(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!current?.canEdit||busy)return;const value=String(new FormData(event.currentTarget).get("plannedAt")??"");const token=generation.current;setPlanned(value);setBusy("plan");setSaveError("");setNotice("");try{const result=await service.updateCandidateInterviewPlan({applicationId,plannedAt:interviewPlannedAt(value),expectedVersion:current.planVersion});if(generation.current!==token)return;setData(previous=>previous?{...previous,plannedAt:result.plannedAt,planVersion:result.version}:previous);setPlanned(localDate(result.plannedAt));setNotice("Interview plan saved. No invitation or reminder was sent.");}catch(error){if(generation.current===token)setSaveError(errorText(error));}finally{if(generation.current===token)setBusy(null);}}
  async function saveItem(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!current?.canEdit||busy)return;const token=generation.current;setBusy("item");setSaveError("");setNotice("");try{const signature=JSON.stringify(draft);if(!request.current||request.current.signature!==signature)request.current={signature,id:crypto.randomUUID()};const fields={question:draft.question,candidateAnswer:draft.candidateAnswer,reviewerObservation:draft.reviewerObservation,sourceReference:draft.sourceReference,verificationState:draft.verificationState};const result=editing?await service.updateCandidateInterviewItem({...fields,itemId:editing.id,expectedVersion:editing.version}):await service.createCandidateInterviewItem({...fields,applicationId,criterionId:draft.criterionId,requestId:request.current.id});if(generation.current!==token)return;setData(previous=>{if(!previous)return previous;const exists=previous.items.some(item=>item.id===result.id);return {...previous,items:exists?previous.items.map(item=>item.id===result.id?result:item):[result,...previous.items]};});setDraft(emptyDraft);setEditing(null);request.current=null;setNotice("Interview record saved. The hiring decision is unchanged.");if(historyItem===result.id)void showHistory(result.id);}catch(error){if(generation.current===token)setSaveError(errorText(error));}finally{if(generation.current===token)setBusy(null);}}
  async function showHistory(itemId:string){const token=++eventGeneration.current;setHistoryItem(itemId);setEvents([]);setHistoryError("");setHistoryBusy(true);try{const result=await service.listCandidateInterviewItemEvents(itemId);if(eventGeneration.current===token)setEvents(result);}catch(error){if(eventGeneration.current===token)setHistoryError(errorText(error));}finally{if(eventGeneration.current===token)setHistoryBusy(false);}}
  const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  return <section className="workspace-card interview-workspace" aria-labelledby={id}><header><p className="section-kicker">Candidate workspace · {candidateName}</p><h2 id={id} ref={heading} tabIndex={-1}>Interview &amp; verification</h2></header><p className="internal-notes-disclosure">Private to authorised members of your company. Interview records are excluded from client summaries and shared reports.</p><p>A candidate explanation is a claim to investigate. Supporting evidence means a reviewer recorded a source; it does not establish that every claim is verified. The human hiring decision stays separate.</p>
    {loadError?<div role="alert"><p>{loadError}</p><button type="button" className="button" onClick={()=>setReload(value=>value+1)}>Retry interview workspace</button></div>:!current?<p role="status">Loading interview workspace…</p>:<>
      <form onSubmit={savePlan}><h3>Interview plan</h3><label>Planned interview date and time ({timezone})<input name="plannedAt" type="datetime-local" value={planned} disabled={!!busy||!current.canEdit} onInput={event=>setPlanned(event.currentTarget.value)} onChange={event=>setPlanned(event.currentTarget.value)}/></label><p className="internal-note-meta">Stored in UTC. Scheduling here does not send invitations or reminders.</p>{current.canEdit&&<button type="submit" className="button" disabled={!!busy}>{busy==="plan"?"Saving plan…":"Save interview plan"}</button>}</form>
      {current.planEvents.length>0&&<details className="interview-plan-history"><summary>View interview schedule history</summary><ol>{current.planEvents.map(entry=><li key={entry.id}><strong>{entry.actorName||"Former reviewer"}</strong> · <time dateTime={entry.createdAt}>{dateLabel(entry.createdAt)}</time><p>{entry.state.plannedAt?`Scheduled for ${dateLabel(entry.state.plannedAt)}`:"Cleared the planned interview date"}</p></li>)}</ol></details>}
      <div className="interview-summary"><h3>Outstanding checks</h3>{interviewUnresolvedItems(current.items).length?<><p>{interviewUnresolvedItems(current.items).length} question(s) still need supporting evidence. Candidate explanations remain in this list.</p><ul>{interviewUnresolvedItems(current.items).map(item=><li key={item.id}>{item.criterionSnapshot.label}: {item.question} — {candidateInterviewVerificationLabels[item.verificationState]}</li>)}</ul></>:<p>{current.items.length?"Each recorded question has a supporting source. Review its reliability before making a decision.":"No interview questions recorded yet."}</p>}</div>
      {current.canEdit?<form onSubmit={saveItem}><h3 ref={composer} tabIndex={-1}>{editing?"Edit interview record":"Prepare a question or record an answer"}</h3><fieldset disabled={!!busy}><label>Role criterion<select required value={draft.criterionId} disabled={!!editing} onChange={event=>setDraft({...draft,criterionId:event.target.value})}><option value="">Choose the requirement to investigate</option>{editing?<option value={draft.criterionId}>{editing.criterionSnapshot.label} (saved criterion)</option>:current.criteria.map(criterion=><option key={criterion.id} value={criterion.id}>{criterion.label}</option>)}</select></label>{editing&&<p>The original criterion is retained for this record. Create another question to use a different criterion.</p>}<label>Question<textarea required maxLength={2000} value={draft.question} onChange={event=>setDraft({...draft,question:event.target.value})} placeholder="Which parts of the payment integration did you deliver personally?"/></label><label>Candidate answer<textarea maxLength={4000} value={draft.candidateAnswer} onChange={event=>setDraft({...draft,candidateAnswer:event.target.value})} placeholder="Record the candidate’s explanation in their context. Leave blank until answered."/></label><label>Reviewer observation<textarea maxLength={4000} value={draft.reviewerObservation} onChange={event=>setDraft({...draft,reviewerObservation:event.target.value})} placeholder="What was clarified, and what still needs checking?"/></label><label>Source / reference<textarea maxLength={2000} value={draft.sourceReference} onChange={event=>setDraft({...draft,sourceReference:event.target.value})} placeholder="Reference call with project lead, 22 September; or a candidate-confirmed project document."/></label><label>Verification state<select value={draft.verificationState} onChange={event=>setDraft({...draft,verificationState:event.target.value as Draft["verificationState"]})}>{CANDIDATE_INTERVIEW_VERIFICATION_STATES.map(state=><option key={state} value={state}>{candidateInterviewVerificationLabels[state]}</option>)}</select></label><p className="internal-note-meta">Candidate explained requires a recorded answer. Supporting evidence added requires a source or reference.</p></fieldset><div className="workflow-actions"><button className="button button-primary" disabled={!!busy||!draft.question.trim()||(!editing&&!draft.criterionId)} type="submit">{busy==="item"?"Saving interview record…":editing?"Save record changes":"Save interview record"}</button>{dirty&&<button type="button" className="button" disabled={!!busy} onClick={()=>{setDraft(emptyDraft);setEditing(null);setSaveError("");request.current=null;}}>Discard question draft</button>}</div></form>:<p>Interview records are read only for your current access.</p>}
      {saveError&&<div role="alert"><p>{saveError} Your unsaved fields remain available.</p><button type="button" className="button" disabled={!!busy} onClick={()=>setReload(value=>value+1)}>Discard drafts and reload latest records</button></div>}{notice&&<p role="status">{notice}</p>}
      <h3>Saved questions and answers</h3>{current.items.length?<ul className="interview-records">{current.items.map(item=><li key={item.id}><CandidateInterviewRecord item={item}/><div className="workflow-actions">{current.canEdit&&<button type="button" className="button" disabled={!!busy||dirty} onClick={()=>{setEditing(item);setDraft({criterionId:item.criterionId??item.criterionSnapshot.id,question:item.question,candidateAnswer:item.candidateAnswer,reviewerObservation:item.reviewerObservation,sourceReference:item.sourceReference,verificationState:item.verificationState});setNotice("");setSaveError("");composer.current?.focus();}}>Edit interview record</button>}<button type="button" className="button" onClick={()=>void showHistory(item.id)}>View edit history</button></div>{historyItem===item.id&&<div><h4>Record history</h4>{historyBusy?<p role="status">Loading interview history…</p>:historyError?<div role="alert"><p>{historyError}</p><button type="button" className="button" onClick={()=>void showHistory(item.id)}>Retry history</button></div>:<ol className="internal-note-history">{events.map(entry=><li key={entry.id}><strong>{entry.actorName||"Former reviewer"}</strong> · <time dateTime={entry.createdAt}>{dateLabel(entry.createdAt)}</time><CandidateInterviewRecord item={entry.state}/></li>)}</ol>}</div>}</li>)}</ul>:<p>No saved questions or answers.</p>}
    </>}{onClose&&<button type="button" className="button" disabled={!!busy} onClick={onClose}>{dirty||planned!==localDate(current?.plannedAt??null)?"Close interview / discard unsaved fields":"Close interview workspace"}</button>}
  </section>;
}
