import { assertEquals } from "jsr:@std/assert@1.0.16";
import { handleAnalyzePublicEvidence, validatePublicEvidenceAnalysis } from "../analyze-public-evidence/index.ts";

type Call={name:string;args:Record<string,unknown>};
const claim={sourceId:"source-1",leaseToken:"11111111-1111-4111-8111-111111111111",jobTitle:"Mobile Developer",criteria:[{id:"criterion-1",label:"Ship mobile applications"}],resumeEvidence:[]};
function client(allowed=true){const calls:Call[]=[];return{calls,auth:{getUser:async(token:string)=>token==="valid"?{data:{user:{id:"user-1"}},error:null}:{data:{user:null},error:new Error("invalid")}},rpc:async(name:string,args:Record<string,unknown>)=>{calls.push({name,args});if(name==="prepare_public_evidence_analysis")return allowed?{data:claim,error:null}:{data:null,error:{message:"forbidden"}};return{data:{status:"ready"},error:null};}};}
function request(body:object,token="valid"){return new Request("https://example.test/analyze-public-evidence",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});}
const input={reportId:"report-1",sourceType:"portfolio",sourceUrl:"https://example.com/work",sourceTitle:"Mobile app case study",sourceExcerpt:"A public case study describing a mobile release.",candidateConfirmed:true};
const output={summary:"The source adds delivery context that requires human verification.",requirementLinks:[{criteriaId:"criterion-1",finding:"The case study describes a released mobile application.",status:"Supporting evidence",verificationNeeded:"Confirm authorship and release date."}],additionalFacts:["The source names a public release."],verificationQuestions:["Which parts of the release did you personally deliver?"]};

Deno.test("public evidence rejects unauthenticated requests before analysis",async()=>{let providers=0;const response=await handleAnalyzePublicEvidence(request(input,"bad"),{adminClient:client() as never,providerTransport:async()=>{providers++;return JSON.stringify(output);}});assertEquals(response.status,401);assertEquals(providers,0);});
Deno.test("public evidence rejects access outside the active company",async()=>{let providers=0;const response=await handleAnalyzePublicEvidence(request(input),{adminClient:client(false) as never,providerTransport:async()=>{providers++;return JSON.stringify(output);}});assertEquals(response.status,403);assertEquals(providers,0);});
Deno.test("public evidence stores only validated analysis",async()=>{const fake=client();const response=await handleAnalyzePublicEvidence(request(input),{adminClient:fake as never,providerTransport:async()=>JSON.stringify(output)});assertEquals(response.status,200);assertEquals(fake.calls.map(c=>c.name),["prepare_public_evidence_analysis","finalize_public_evidence_analysis"]);});
Deno.test("public evidence blocks decision language",()=>{let failed=false;try{validatePublicEvidenceAnalysis({...output,summary:"This is the best candidate."},claim.criteria);}catch{failed=true;}assertEquals(failed,true);});
Deno.test("public evidence fails an unsafe provider result",async()=>{const fake=client();const response=await handleAnalyzePublicEvidence(request(input),{adminClient:fake as never,providerTransport:async()=>JSON.stringify({...output,summary:"Hire this person."})});assertEquals(response.status,422);assertEquals(fake.calls.at(-1)?.name,"fail_public_evidence_analysis");});
