-- Route-level product facts for generative support. These are verified capabilities,
-- not customer-facing scripts; the model composes a contextual answer at runtime.

insert into public.support_knowledge_base_articles (
  slug, title, body, status, approved_by_platform_user_id, approved_at, updated_at
)
select seed.slug, seed.title, seed.body, 'approved', owner.user_id, now(), now()
from (
  select user_id from public.platform_change_owners
  where status = 'active' order by created_at limit 1
) owner
cross join (
  values
    ('product-navigation','Workspace navigation and starting point','Dashboard shows workflow status and review items. Jobs is where a company creates a role and its job-related criteria. Each job opens a Candidates list with upload and report actions. Pilot access shows the active term, usage, limits, pricing and ongoing-access request. Privacy and data records candidate information requests for human handling. Support records problems and feature requests. When a customer asks generally how to start, use the current route. From Dashboard or Jobs, direct a new customer to create the role and its first requirement. Give the next two or three actions rather than describing every feature at once.'),
    ('jobs-and-requirements','Jobs, criteria, and examples','On /jobs, the user can create a job with role title, optional department and location, and between 1 and 12 requirements. At least one requirement must be marked Required. A requirement is one observable job-related skill, responsibility, qualification, or type of experience. The optional evidence field explains what proof to look for. Create examples that fit the role named by the customer. For a Frontend Developer, examples include building React interfaces, integrating REST APIs, testing production interfaces, accessibility work, or production deployment experience. Do not use personal characteristics. Different titles can describe similar work: reports assess the entered requirements, not an exact title-name match.'),
    ('candidate-list-and-upload','Candidate list and private document upload','On /jobs/:jobId/candidates, the user sees candidate document and report states. View report opens a completed evidence report. Review source opens the manual/source review flow when a report is not ready. Upload opens /jobs/:jobId/candidates/upload. Upload accepts PDF or DOCX files up to 10 MB each. The user must confirm the organisation has permission or another valid basis to process the documents. Files are private and company-scoped. After upload, direct the user back to Candidates and then Review source. Never ask a customer to paste candidate content into support chat.'),
    ('source-review-and-ai','Source review and AI-assisted analysis','On /jobs/:jobId/candidates/:documentId/manual-review, the user can open the private source. Manual review requires selecting a job requirement, recording source-grounded evidence and a source reference, then optionally recording missing evidence and verification needed. For AI assistance, the browser extracts PDF or DOCX text locally. The user reviews the preview and acknowledges that the text will be sent to the configured AI provider. Incomplete or truncated extraction cannot be sent and must use manual review. The AI output is a draft for human review.'),
    ('evidence-report-workflow','Evidence report and human decision','On /reports/:reportId, review each requirement together with its evidence, source reference, missing-evidence note and verification need. The report may prepare verification or interview questions. It does not rank candidates or make the hiring decision. The hiring team chooses the outcome and must enter a written job-related reason. Useful guidance tells the user which section to inspect next and reminds them to verify uncertain evidence. Never recommend a final candidate outcome.'),
    ('access-pricing-and-users','Pilot access, ongoing access, and users','The controlled paid pilot is S$500 for 30 days, one role, up to 50 new candidate documents and up to two named company users. It does not renew automatically. Pilot access starts only when the approved customer selects Start pilot. Ongoing access is requested separately. The founding offer is S$800 for each of the first three 30-day ongoing terms, with up to 10 active roles, 500 new documents and five named users; the disclosed standard price is S$1,400 from term four. One user normally belongs to one active company workspace. Special company access is a controlled and auditable owner-approved exception. Use the live Pilot access page values when the customer asks about their own remaining days or usage.'),
    ('account-and-recovery','Sign-in, invitations, and password recovery','Approved users set their password through the invitation link and then sign in with that same email. Forgot password sends a recovery link; the customer should open the newest email, including checking spam when necessary, and set a new password. A pilot request records the company request for review; it does not immediately activate access or start billing. Access approval and special-company exceptions are handled by the platform owner. Never ask for a password, recovery token, invitation token, or authentication code.'),
    ('privacy-support-and-boundaries','Privacy requests, support, and safe boundaries','On /workspace/privacy, a company user records a candidate access, correction, deletion or withdrawal request. Recording the request does not itself export, correct, withdraw or delete data. An administrator verifies identity and records a written human review outcome; any data action is a separate authorised process. On /workspace/support, users can report a problem or request a feature with summary, priority, details and safe page diagnostics. Support chat excludes candidate names, documents, passwords, tokens and confidential records. The Guide can explain implemented workflows and create relevant examples. It cannot change records, access, code, deployment or configuration, and it must say when supplied facts are insufficient.' )
) as seed(slug, title, body)
on conflict (slug) do update
set title = excluded.title,
    body = excluded.body,
    status = 'approved',
    approved_by_platform_user_id = excluded.approved_by_platform_user_id,
    approved_at = excluded.approved_at,
    updated_at = excluded.updated_at;
